#####################################################################################
## [RHEL_Patches_reboot.yml]
## --
## Authors        : Renato Alexandre da Rocha (ralex@br.ibm.com) @ralex 
## Squad          : GI_SSI_OM_S1 Squad
## 
#####################################################################################

#####################################################################################
## Script Purpose : Playbook to perform 'yum update' on selected hosts.
##                  This playbook will also reboot hosts if kernel is updated.
##
## Supported OS:  RHEL
#####################################################################################

---
- name: Performing yum update on host(s) excluding the Kernel and GLIBC
  hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  any_errors_fatal: false

  vars:
        pre_update_script: /var/log/checklist/RHEL_pre_update_without_reboot.sh

  pre_tasks:

          ##########################################################################
          ## pre_update script
          ##########################################################################
        
          - name: Create the directory /var/log/checklist if it does not exist
            file:
              path: /var/log/checklist
              state: directory
              mode: '0775'

          - name: Copying pre-update script to server
            copy: src=RHEL_pre_update_without_reboot.sh dest=/var/log/checklist/RHEL_pre_update.sh owner=root group=root mode=775

          - name: Checking if pre update script exist
            stat:
              path: '{{ pre_update_script }}'
            register: pre_update_file
