#####################################################################################
## [RHEL_Patches_reboot.yml]
## --
## Authors        : Renato Alexandre da Rocha (ralex@br.ibm.com) @ralex 
## Squad          : GI_SSI_OM_S1 Squad
## 
#####################################################################################

#####################################################################################
## Script Purpose : Playbook to perform 'yum update' on selected hosts.
##                  This playbook will also reboot hosts if kernel is updated.
##
## Supported OS:  RHEL
#####################################################################################

---
- name: Performing yum update on host(s) excluding the Kernel and GLIBC
  hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  any_errors_fatal: false

  vars:
        pre_update_script: /var/log/checklist/RHEL_pre_update_without_reboot.sh
        post_update_script: /var/log/checklist/RHEL_post_update.sh

  pre_tasks:

          ##########################################################################
          ## pre_update script
          ##########################################################################
        
          - name: Create the directory /var/log/checklist if it does not exist
            file:
              path: /var/log/checklist
              state: directory
              mode: '0775'

          - name: Copying pre-update script to server
            copy: src=RHEL_pre_update_without_reboot.sh dest=/var/log/checklist/RHEL_pre_update.sh owner=root group=root mode=775

          - name: Checking if pre update script exist
            stat:
              path: '{{ pre_update_script }}'
            register: pre_update_file

          - name: Running pre update script
            command: /bin/bash '{{ pre_update_script }}'
            when: pre_update_file.stat.exists == true
            ignore_errors: no
            
  
          ###########################################################################
          ## post_update script
          ###########################################################################
         
  post_tasks:

          - name: Copying post-update script to server
            copy: src=RHEL_post_update.sh dest=/var/log/checklist/RHEL_post_update.sh owner=root group=root mode=775

          - name: Checking if post update script exist
            stat:
              path: '{{ post_update_script }}'
            register: post_update_file 

          - name: Running post update script
            command: /bin/bash '{{ post_update_script }}'
            when: post_update_file.stat.exists == true
            ignore_errors: no

          - name: Delete pre-update script
            file:
              path: /var/log/checklist/RHEL_pre_update.sh
              state: absent
        
          - name: Delete post-update script
            file: 
              path: /var/log/checklist/RHEL_post_update.sh
              state: absent

          - debug:
              msg: Security patch update completed.
